### PR TITLE
Add WISO SSO and make user options provider dependent

### LINKED ISSUE #12: WISO Zugang für Studierende
Einige Hochschulen und Universitäten bieten den Studierenden einen Zugang zu WISO. Diese bieten Zeitungsartikel an. Die Authentifizierung findet über den SSO der Hochschule/Uni statt.

**URL des Digitalangebots der Bibliothek**
[https://www.wiso-net.de/](https://www.wiso-net.de/)

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
Auf der Webseite steht "Provided by Genios", daher denke ich dass es sich um Genios hadelt

### PR DESCRIPTION
**Pull request by PascalKoe**
Moved the user options into provider specific fields so you can store different credentials for different providers. This allows to store the configuration for the WISO SSO provider, which needs a city an the name of the university.

WISO redirects you to your SSO page, so if you aren't logged in in regards to your SSO provider, then you have to sign in manually and reload the article to retrigger the voebbot.

Fixes #12

### CODE REVIEW

**Comment by stefanw** [comment]
Good idea! This needs an upgrade path from the current storage of username/password though.

**Comment by PascalKoe** [comment]
Probably needs adjustment of the condition when the update is run or the right version bump.

**Comment by stefanw** [comment]
I removed the busy loop in https://github.com/stefanw/voebbot/commit/9f762e3abf14b1e254dc864c3cd5d4d7f3459738

Could you try if this works for you?

**Comment by PascalKoe** [comment]
Seems to work like it should

**Pull request merged**
